[Mesh]
  # Declare a mesh to solve SN neutron transport on. Here, we use the same mesh that Cardinal uses to
  # generate MGXS.
  [NeutronicsDomain]
    type = FileMeshGenerator
    file = mesh_in.e
  []
[]

# This is a custom input block in Gnat that sets up the SN transport problem, where we essentially tell
# Gnat how we want it to solve our problem. It's similar to OpenMCCellAverageProblem in Cardinal.
[TransportSystems]
  [Neutron]
    # We specify the number of energy groups here. This should match the number of energy groups
    # you specified when generating MGXS in Cardinal
    num_groups = 3

    # We specify the maximum degree of angular flux moments for the transport system to add. This
    # should be less than or equal to the number of scattering cross section Legendre moments
    # generated by Cardinal.
    max_anisotropy = 0

    # You should always set these two. The first is our numerical scheme (the Self-Adjoint Angular Flux formalism)
    # and the second is the type of particle we're simulating (neutron).
    scheme = saaf_cfem
    particle_type = neutron

    # The name of the output scalar flux variables (/ higher order angular flux moments).
    flux_moment_names = 'Flux_Moment'

    # Fission is still technically "experimental" in Gnat, so you have to specifically enable it
    # with this flag.
    debug_disable_fission = false

    # This flag says we're solving the eigenvalue (k_eff) form of the neutron transport equation.
    # Setting constant_ic = '1.0' fixes a bug where the problem fails to converge.
    eigen = true
    constant_ic = '1.0'

    # The spatial discretization variable type (family) and the spatial discretization order. Unless
    # you really know what you're doing, always use LAGRANGE and FIRST.
    family = LAGRANGE
    order = FIRST

    # The number of angles to use for the SN approximation.
    n_azimuthal = 3
    n_polar = 3

    # You'd set vacuum / reflective boundary conditions with these flags. They must correspond to sidesets
    # in the mesh.
    vacuum_boundaries = '10000'
    reflective_boundaries = '10001'
  []
[]

# In this problem, Cardinal doesn't generate MGXS in the air regions as the statistics are terrible.
# We approximate air as void with a TransportMaterial that sets all cross sections to zero.
[TransportMaterials/Void]
  type = VoidTransportMaterial
  block = 'air src src_trimmer_tri'
[]

# This is the block that imports cross sections from Cardinal.
[CardinalMGXS]
  # Since we're doing this "online", we select that we want to pull cross sections from a sub-application.
  # Another option is to load them from a mesh with an exodus restart.
  xs_source = 'subapp'
  # The subapp we want to pull cross sections from.
  from_multi_app = 'cardinal_xs'

  # The transport system we want to apply cross sections to
  transport_system = 'Neutron'
  # The order of scattering anisotropy. This should match the order declared in the MGXS block in Cardinal.
  scatter_anisotropy = 0
  # A flag to say that we want to add fission heating.
  add_fission_heating = true

  # The blocks to apply cross sections to. This is all non-air blocks in this example.
  block = 'fuel cladding graphite_core graphite_reflector stainless_steel
           fuel_trimmer_tri graphite_core_trimmer_tri graphite_reflector_trimmer_tri
           stainless_steel_trimmer_tri'
[]

[MultiApps]
  [cardinal_xs]
    type = FullSolveMultiApp
    app_type = 'CardinalApp'
    execute_on = INITIAL
    input_files = 'openmc.i'
  []
[]

[Executioner]
  type = Eigenvalue

  initial_eigenvalue = 1.2
  normal_factor = 1.0
  normalization = 'TotalFlux'
  free_power_iterations = 6

  solve_type = PJFNK
  #petsc_options_iname = '-pc_type -pc_hypre_type -ksp_gmres_restart'
  #petsc_options_value = ' hypre    boomeramg      600'
  petsc_options_iname = '-ksp_gmres_restart'
  petsc_options_value = ' 600'

  nl_abs_tol = 1e-12

  automatic_scaling = true
  off_diagonals_in_auto_scaling = true
  compute_scaling_once = false
[]

[Postprocessors]
  [TotalFlux]
    type = TotalFluxPostProcessor
    num_groups = 3
    group_scalar_fluxes = 'Flux_Moment_1_0_0 Flux_Moment_2_0_0 Flux_Moment_3_0_0'
    execute_on = LINEAR
    outputs = 'csv'
  []
[]

[VectorPostprocessors]
  [EigenValues]
    type = Eigenvalues
    inverse_eigenvalue = true
  []
[]

[Outputs]
  csv = true
  exodus = true
  execute_on = TIMESTEP_END
[]
