Content:
    Gnat:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: Gnat
        repo: https://github.com/nuclearkevin/gnat
        menu:
            Getting Started:
                Installation: getting_started/installation.md
                Example 1: getting_started/example_1.md
                Example 2: getting_started/example_2.md
                Example 3: getting_started/example_3.md
                Example 4: getting_started/example_4.md
                Other Examples: getting_started/other_examples.md
            Theory and Implementation:
                Governing Equations: about/equations.md
                FEM Stabilization: about/stabilization.md
                NTE Angular Approach: about/nte_angular_approach.md
                Implementation in Moose: about/implementation.md
            Documentation:
                Gnat Syntax Pages: syntax/NeutronActivationStudy/index.md
                Gnat Source Pages: source/index.md
                MOOSE Source Pages: https://mooseframework.inl.gov/source/index.html
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        unregister: !include ${MOOSE_DIR}/framework/doc/unregister.yml
        includes:
            - include
        sources:
            - src
        inputs:
            - examples
            - tests
