Content:
    Gnat:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: Gnat
        repo: https://github.com/OTU-Center-for-Small-Modular-Reactors/gnat
        menu:
            Getting Started:
                Installation: getting_started/installation.md
                Tutorials: tutorials/index.md
            Theory and Implementation:
                Radiation Transport: about/radiation_transport.md
                Fluid Depletion: about/mobile_depletion.md
                Implementation: about/implementation.md
            Documentation:
                Gnat Source Pages: source/index.md
                MOOSE Source Pages: https://mooseframework.inl.gov/source/index.html
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        unregister: !include ${MOOSE_DIR}/framework/doc/unregister.yml
        includes:
            - include
        sources:
            - src
        inputs:
            - examples
            - tests
